receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_GRPC_ENDPOINT}
      http:
        endpoint: ${env:OTEL_HTTP_ENDPOINT}

processors:
  batch:

exporters:

  debug:
    verbosity: detailed

  otlphttp/jaeger:
    endpoint: ${env:JAEGER_URL}

  otlphttp/tracepilot:
    endpoint: ${env:TRACEPILOT_URL}

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/jaeger, otlphttp/tracepilot]
