receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_GRPC_ENDPOINT}
      http:
        endpoint: ${env:OTEL_HTTP_ENDPOINT}

processors:
  batch:

exporters:

  debug:
    verbosity: detailed

  otlp/jaeger:
    endpoint: ${env:JAEGER_HOST}:4317
    tls:
      insecure: true

  otlphttp/tracepilot:
    endpoint: http://${env:TRACEPILOT_HOSTPORT}

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger, otlphttp/tracepilot]
