spring.application.name = order_service
server.port=${PORT:8081}
services.inventory.base-url=${INVENTORY_SERVICE_URL:http://localhost:8083}
services.payment.base-url=${PAYMENT_SERVICE_URL:http://localhost:8082}
